"""deco_pope — Mode-1 container input: frozen cases + protocol -> VLDiagnoseLoop.

This script is the *input* to the diagnosis agent, mirroring
examples/qwen_loop_agy/run.py:

    1. load data/cases/{model}.json     (frozen fail+success manifest, mine_cases.py)
    2. drift check                      (re-generate a sample, compare frozen labels)
    3. ExperimentProtocol               (DESIGN.md §5 — anchors M1 selection + M5 vetting)
    4. VLDiagnoseLoop M1→M5             (existing analyzers; pope picks up
                                         metadata["pope_label"] automatically)
    5. loop.run_m4(report, cases)       (fix proposal — DeCo rescoring, see TODO.md Step 4)

No package modifications: any bespoke probe/fix the diagnosis needs lives in
THIS directory (deco_probe.py / deco_fix.py, written per TODO.md) or is
generated by the loop's tier-(b) probe generator.

Usage:
    python run.py --model qwen3-vl-2b-instruct          # full loop
    python run.py --smoke-test                          # manifest schema check, no GPU
    python run.py --skip-m4                             # diagnosis only
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

DATA = Path(__file__).parent / "data"
OUT = Path(__file__).parent / "outputs"
CFG = yaml.safe_load((Path(__file__).parent / "config.yaml").read_text())


# ---------------------------------------------------------------------------
# 1. Frozen manifest -> CaseBatch (mixed PASS/FAIL — M2/M5 need both groups)
# ---------------------------------------------------------------------------

def load_manifest(model_key: str):
    from evalvitals.core.case import CaseBatch, FailureCase, Inputs, Label

    path = DATA / "cases" / f"{model_key}.json"
    if not path.exists():
        raise SystemExit(f"{path} missing — run `python mine_cases.py --model {model_key}` first "
                         f"(see TODO.md Step 1)")
    raw = json.loads(path.read_text())
    cases = []
    for r in raw["cases"]:
        cases.append(FailureCase(
            inputs=Inputs(prompt=raw["prompt_template"].format(obj=r["object"]),
                          image=str(DATA / "images" / r["file_name"])),
            expected=r["pope_label"],
            observed=r["observed"],
            label=Label.FAIL if r["label"] == "fail" else Label.PASS,
            tags={"hallucination", "deco"},
            metadata={k: r[k] for k in (
                "image_id", "object", "probe_type", "pope_label",
                "gt_token_ids", "out_token_ids", "split")},
        ))
    return CaseBatch(cases), raw


def drift_check(model, cases, n: int = 10) -> None:
    """Frozen labels must still reproduce (greedy). See DESIGN.md §4.3."""
    from evalvitals.analyzers.hallucination.pope import parse_yes_no
    stale = 0
    for case in list(cases)[:n]:
        if parse_yes_no(model.generate(case.inputs)) != parse_yes_no(case.observed):
            stale += 1
    if stale:
        print(f"[WARN] {stale}/{n} frozen labels no longer reproduce — re-run mine_cases.py "
              f"(check transformers version vs manifest record)")


# ---------------------------------------------------------------------------
# 2. Protocol — the human prior anchoring the loop (verbatim from DESIGN.md §5)
# ---------------------------------------------------------------------------

def build_protocol():
    from evalvitals.eval_agent.stages.protocol import ExperimentProtocol

    return ExperimentProtocol(
        description=(
            "The VLM answers 'Yes' to object-presence questions about objects that are "
            "NOT in the image, specifically objects that frequently co-occur with objects "
            "that ARE present (e.g. sees keyboard+monitor, hallucinates 'mouse'). "
            "Suspected mechanism (DeCo, arXiv 2410.11779): the model recognizes the "
            "object's absence in intermediate layers, but strong language priors "
            "suppress this in the final layers. Failure cases are wrong answers to "
            "adversarial absent-object probes; success cases are correct answers to "
            "the same probe types on the same images."
        ),
        task_domain="object hallucination",
        success_criteria="parse_yes_no(answer) matches the POPE gold label",
        failure_patterns=(
            "wrong 'Yes' concentrated on high-co-occurrence absent objects; "
            "random-absent and present probes mostly correct"
        ),
        target_modalities=frozenset({"text", "image"}),
    )


# ---------------------------------------------------------------------------
# 3. Loop wiring (mirrors examples/qwen_loop_agy/run.py)
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=CFG["model"])
    ap.add_argument("--max-cycles", type=int, default=2)
    ap.add_argument("--max-analyzers", type=int, default=3)
    ap.add_argument("--smoke-test", action="store_true")
    ap.add_argument("--skip-m4", action="store_true")
    args = ap.parse_args()
    OUT.mkdir(exist_ok=True)

    if args.smoke_test:
        _, raw = load_manifest(args.model) if (DATA / "cases" / f"{args.model}.json").exists() \
            else (None, None)
        print("smoke ok" if raw else "smoke: no manifest yet (expected before Step 1)")
        return

    from evalvitals import compose
    from evalvitals.core.capability import Capability
    from evalvitals.eval_agent import AgyModel, RunLogger, VLDiagnoseLoop
    from evalvitals.eval_agent.stages.diagnosis import DiagnosisAgent
    from evalvitals.eval_agent.stages.probe_agent import ProbeAgent
    from evalvitals.eval_agent.stages.stats_agent import StatsAnalysisAgent

    model = compose(args.model, "hf_local",
                    want={Capability.GENERATE, Capability.HIDDEN_STATES,
                          Capability.ATTENTION})
    cases, raw = load_manifest(args.model)
    print(f"cases={len(list(cases))} yields={raw['yields']}")
    drift_check(model, cases)

    # TODO(Step 0): judge — AgyModel needs the agy binary mounted (see
    # docker-compose.yml); swap for any GENERATE-capable Model if preferred.
    judge = AgyModel()

    # TODO(Step 3): if tier-(a) analyzers don't surface the layer-suppression
    # signal, pass a WhiteboxProbeGenerator to ProbeAgent, or point the loop at
    # ./deco_probe.py (spec in DESIGN.md §6). Window/tau/alpha grid: config.yaml.
    loop = VLDiagnoseLoop(
        model=model,
        probe_agent=ProbeAgent(max_analyzers=args.max_analyzers),
        stats_agent=StatsAnalysisAgent(judge=judge),
        diagnosis_agent=DiagnosisAgent(judge=judge),
        max_cycles=args.max_cycles,
        protocol=build_protocol(),
        run_logger=RunLogger(),  # TODO(verify): out_dir kwarg -> OUT / "logs"
    )
    report = loop.run(cases)
    print("resolved:", report.resolved)
    for h in report.final_hypotheses:
        print(" -", getattr(h, "status", "?"), getattr(h, "statement", h))

    if not args.skip_m4:
        # TODO(Step 4): inject verify_fn wrapping ./deco_fix.py:deco_rescore_answer
        # so M4 verifies the DeCo fix (flip vs regression + guards, DESIGN.md §6).
        fix = loop.run_m4(report, cases)
        print("m4:", fix)


if __name__ == "__main__":
    main()
