"""deco_pope — Mode-1 container input: frozen cases + protocol -> VLDiagnoseLoop.

This script is the *input* to the diagnosis agent, mirroring
examples/qwen_loop_agy/run.py:

    1. load data/cases/{model}.json     (frozen fail+success manifest, mine_cases.py)
    2. drift check                      (re-generate a sample, compare frozen labels)
    3. ExperimentProtocol               (DESIGN.md §5 — anchors M1 selection + M5 vetting)
    4. VLDiagnoseLoop M1→M5             (existing analyzers; pope picks up
                                         metadata["pope_label"] automatically)
    5. loop.run_m4(report, cases)       (fix proposal — DeCo rescoring, see TODO.md Step 4)

No package modifications: any bespoke probe/fix the diagnosis needs lives in
THIS directory (deco_probe.py / deco_fix.py, written per TODO.md) or is
generated by the loop's tier-(b) probe generator.

Usage:
    python run.py --model qwen3-vl-2b-instruct          # full loop
    python run.py --smoke-test                          # manifest schema check, no GPU
    python run.py --skip-m4                             # diagnosis only
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

DATA = Path(__file__).parent / "data"
OUT = Path(__file__).parent / "outputs"
CFG = yaml.safe_load((Path(__file__).parent / "config.yaml").read_text())


# ---------------------------------------------------------------------------
# 1. Frozen manifest -> CaseBatch (mixed PASS/FAIL — M2/M5 need both groups)
# ---------------------------------------------------------------------------

def load_manifest(model_key: str, max_clean_images: int = 0, seed: int = 42):
    """Build the CaseBatch; optionally shrink it BY IMAGE for faster runs.

    max_clean_images > 0 keeps every image with >=1 FAIL (full triplets, so
    all failures and their same-image controls survive) plus a split-stratified
    random sample of clean images. Pairing/cluster structure is intact; only
    the absolute fail rate is enriched — fine for group contrasts and paired
    McNemar, meaningless for tests against an absolute base rate.
    """
    import random as _random

    from PIL import Image

    from evalvitals.core.case import CaseBatch, FailureCase, Inputs, Label

    path = DATA / "cases" / f"{model_key}.json"
    if not path.exists():
        raise SystemExit(f"{path} missing — run `python mine_cases.py --model {model_key}` first "
                         f"(see TODO.md Step 1)")
    raw = json.loads(path.read_text())
    if max_clean_images:
        fail_imgs = {r["image_id"] for r in raw["cases"] if r["label"] == "fail"}
        split_of = {r["image_id"]: r["split"] for r in raw["cases"]}
        clean = sorted({r["image_id"] for r in raw["cases"]} - fail_imgs)
        rng = _random.Random(seed)
        keep = set(fail_imgs)
        for split, frac in (("explore", 0.6), ("validate", 0.4)):
            pool = [i for i in clean if split_of[i] == split]
            keep |= set(rng.sample(pool, min(round(max_clean_images * frac), len(pool))))
        raw["cases"] = [r for r in raw["cases"] if r["image_id"] in keep]
        print(f"subset: kept {len(keep)} images ({len(fail_imgs)} with fails + "
              f"{len(keep) - len(fail_imgs)} clean) -> {len(raw['cases'])} cases")
    cases = []
    pil_cache: dict[str, object] = {}  # the processor rejects str paths; one PIL per image
    for r in raw["cases"]:
        if r["file_name"] not in pil_cache:
            pil_cache[r["file_name"]] = Image.open(DATA / "images" / r["file_name"]).convert("RGB")
        cases.append(FailureCase(
            inputs=Inputs(prompt=raw["prompt_template"].format(obj=r["object"]),
                          image=pil_cache[r["file_name"]]),
            expected=r["pope_label"],
            observed=r["observed"],
            label=Label.FAIL if r["label"] == "fail" else Label.PASS,
            tags={"hallucination", "deco"},
            metadata={k: r[k] for k in (
                "image_id", "object", "probe_type", "pope_label",
                "gt_token_ids", "out_token_ids", "split")},
        ))
    return CaseBatch(cases), raw


def drift_check(model, cases, n: int = 10) -> None:
    """Frozen labels must still reproduce (greedy). See DESIGN.md §4.3."""
    from evalvitals.analyzers.hallucination.pope import parse_yes_no
    stale = 0
    for case in list(cases)[:n]:
        if parse_yes_no(model.generate(case.inputs)) != parse_yes_no(case.observed):
            stale += 1
    if stale:
        print(f"[WARN] {stale}/{n} frozen labels no longer reproduce — re-run mine_cases.py "
              f"(check transformers version vs manifest record)")


# ---------------------------------------------------------------------------
# 2. Protocol — the human prior anchoring the loop (verbatim from DESIGN.md §5)
# ---------------------------------------------------------------------------

def build_judge(model_name: str, effort: str):
    """Claude CLI judge for M2/M3/M5 (agy quota exhausted — swapped 2026-06-12).

    Default claude-fable-5 at low effort; pass --judge-model sonnet|haiku for
    cheap wiring tests. A tiny generation probe catches dead sessions early
    (an empty response means rate-limit/quota, not an error exit).
    """
    from evalvitals.eval_agent import ClaudeModel

    judge = ClaudeModel(model=model_name, effort=effort)
    if not judge.generate("Reply with exactly the word OK").strip():
        raise SystemExit(f"judge probe: claude --model {model_name} returned empty "
                         f"(rate-limited?) — try --judge-model sonnet or haiku")
    print(f"judge: claude model={model_name} effort={effort or 'default'}")
    return judge


def build_protocol():
    from evalvitals.eval_agent.stages.protocol import ExperimentProtocol

    return ExperimentProtocol(
        description=(
            "The VLM answers 'Yes' to object-presence questions about objects that are "
            "NOT in the image, specifically objects that frequently co-occur with objects "
            "that ARE present (e.g. sees keyboard+monitor, hallucinates 'mouse'). "
            "Failure cases are wrong answers to "
            "adversarial absent-object probes; success cases are correct answers to "
            "the same probe types on the same images."
        ),
        task_domain="object hallucination",
        success_criteria="parse_yes_no(answer) matches the POPE gold label",
        failure_patterns=(
            "wrong 'Yes' concentrated on high-co-occurrence absent objects; "
            "random-absent and present probes mostly correct"
        ),
        target_modalities=frozenset({"text", "image"}),
    )


# ---------------------------------------------------------------------------
# 3. Loop wiring (mirrors examples/qwen_loop_agy/run.py)
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=CFG["model"])
    ap.add_argument("--max-cycles", type=int, default=2)
    ap.add_argument("--max-analyzers", type=int, default=3)
    ap.add_argument("--smoke-test", action="store_true")
    ap.add_argument("--skip-m4", action="store_true")
    ap.add_argument("--judge-model", default=CFG.get("judge_model", "claude-fable-5"))
    ap.add_argument("--judge-effort", default=CFG.get("judge_effort", "low"))
    ap.add_argument("--max-clean-images", type=int, default=0,
                    help="shrink input by image: keep all fail-images + this many "
                         "clean images (0 = use the full manifest)")
    # Explicit single device — NOT device_map="auto". accelerate's auto-dispatch
    # leaves meta tensors and its per-forward hooks are not thread-safe, which
    # crashed white-box analyzers and ballooned GPU memory to OOM under the M1
    # parallel probe. Mirrors examples/qwen_loop_claude (--device cuda).
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--dtype", default="bfloat16")
    args = ap.parse_args()
    OUT.mkdir(exist_ok=True)

    if args.smoke_test:
        _, raw = load_manifest(args.model) if (DATA / "cases" / f"{args.model}.json").exists() \
            else (None, None)
        print("smoke ok" if raw else "smoke: no manifest yet (expected before Step 1)")
        return

    from evalvitals import compose
    from evalvitals.core.capability import Capability
    from evalvitals.eval_agent import (
        CliAgentConfig,
        ExperimentWriterConfig,
        FixAgent,
        RunLogger,
        SurgeryAgent,
        VLDiagnoseLoop,
    )
    from evalvitals.eval_agent.stages.diagnosis import DiagnosisAgent
    from evalvitals.eval_agent.stages.probe_agent import ProbeAgent
    from evalvitals.eval_agent.stages.stats_agent import StatsAnalysisAgent
    from evalvitals.models.backends.base import RuntimeConfig

    judge = build_judge(args.judge_model, args.judge_effort)  # probe BEFORE weights load

    model = compose(args.model, "hf_local",
                    runtime=RuntimeConfig(device=args.device, dtype=args.dtype),
                    want={Capability.GENERATE, Capability.HIDDEN_STATES,
                          Capability.ATTENTION})
    cases, raw = load_manifest(args.model, max_clean_images=args.max_clean_images)
    print(f"cases={len(list(cases))} yields={raw['yields']}")
    drift_check(model, cases)

    # PIPELINE AUTONOMY: this run.py only provides inputs (frozen cases +
    # protocol). Detection, custom probing (tier-(b) codegen), diagnosis and
    # repair are all done by the loop's own agents. Reference analyses are
    # kept OUTSIDE this repository so the loop's coding agents cannot read
    # them (DESIGN.md §6: they grade the loop's conclusions, not feed them).
    codegen_effort = str(CFG.get("codegen_effort", "") or "")
    codegen = CliAgentConfig(
        provider="claude_code",
        model=str(CFG.get("codegen_model", "sonnet")),
        max_budget_usd=float(CFG.get("codegen_budget_usd", 2.0)),
        timeout_sec=int(CFG.get("codegen_timeout_sec", 240)),
        # claude -p --effort <level>; appended verbatim to the CLI command
        extra_args=(("--effort", codegen_effort) if codegen_effort else ()),
    )
    print(f"codegen: claude_code model={codegen.model} "
          f"effort={codegen_effort or 'default'}")
    run_logger = RunLogger(run_dir=OUT / "logs", verbose=True)
    loop = VLDiagnoseLoop(
        model=model,
        # judge => LLM-guided analyzer selection anchored on the protocol
        # (static StrategyProbe picks generic attention analyzers, not pope);
        # allow_codegen => tier-(b): the loop writes its own probe when the
        # catalog can't surface the mechanism (need_custom) OR when selected
        # analyzers fail at runtime; white/black-box generators are built
        # lazily from judge + codegen_config.
        probe_agent=ProbeAgent(
            judge=judge, max_analyzers=args.max_analyzers,
            allow_codegen=True, codegen_config=codegen,
        ),
        stats_agent=StatsAnalysisAgent(judge=judge, allow_codegen=True,
                                       codegen_config=codegen),
        diagnosis_agent=DiagnosisAgent(judge=judge),
        surgery_agent=SurgeryAgent(
            judge=judge, writer_config=ExperimentWriterConfig(cli_agent=codegen)),
        # Bound fix validation: a coded pipeline calls the model ~k times PER
        # case, so validating on the full batch times out (run#2: 4418 calls,
        # 600s kill). Validate on a label-stratified subset and allow more wall
        # clock for the coded path.
        fix_agent=FixAgent(judge=judge,
                           max_tier=str(CFG.get("fix_max_tier", "L3b")),
                           cli_config=codegen, run_logger=run_logger,
                           max_validation_cases=int(CFG.get("fix_validation_cases", 60)),
                           exec_timeout_sec=int(CFG.get("fix_exec_timeout_sec", 900)),
                           max_repair_rounds=int(CFG.get("fix_repair_rounds", 1))),
        max_cycles=args.max_cycles,
        protocol=build_protocol(),
        run_logger=run_logger,
    )
    report = loop.run(cases)
    print(f"cycles={report.cycles} stopped_by={report.stopped_by} "
          f"verified={len(report.verified_hypotheses)}/{len(report.all_test_results)}")
    for t in report.all_test_results:
        stmt = getattr(t.hypothesis, "statement", str(t.hypothesis))
        print(f" - [{t.status}] conf={t.confidence:.2f} grade={t.evidence_grade} {stmt[:110]}")

    if not args.skip_m4:
        # Repair is the loop's job too: M4 surgery on the best verified
        # hypothesis (no-op when none verified), then the tiered fix module
        # (falls back to the last cycle's proposals; validates candidates
        # with paired McNemar against the unmodified baseline).
        fix = loop.run_m4(report, cases)
        print("m4:", fix)
        outcome = loop.run_fix(report, cases)
        print("fix outcome:", getattr(outcome, "recommendation", None) or outcome)


if __name__ == "__main__":
    main()
